### ISSUE TITLE
installation doc not up to date

### ISSUE THREAD

**Issue by JanickRoss** [cblegare/cookiecutter-py#3]
Change
 cookiecutter https://github.com/abstrus/cookiecutter-py.git 
to
 cookiecutter https://github.com/cblegare/cookiecutter-py.git

and 

change 
pip install -r requirements_dev.txt
to
pip install -r requirements/dev.txt

**Comment by cblegare** [comment]
Thank you.  Feel free to tell if you fin any other issues like these.
