### ISSUE TITLE
Add support to flask-restful

### ISSUE THREAD

**Issue by JanickRoss** [cblegare/cookiecutter-py#4]
Is it possible to add the flask-restful support by adding a choice when creating the coookiecutter when answering yes for using APIs

**Comment by cblegare** [comment]
I wont _add_ support for a REST framework, but I may change the current framework used in the template.  The `web.py` module is already somewhat broken and counter-intuitive, expect drastic changes pretty soon.  Also, I may use flask-restplus instead of flask-restful
